
general {
        output_format = "i3bar"
        colors = true
        interval = 5
        color_good = "#b8bb26"
        color_degraded = "#fabd2f"
        color_bad = "#fb4934"
}

order += "wireless _first_"
order += "ethernet _first_"
order += "cpu_usage"
order += "cpu_temperature 0"

wireless _first_ {
        # Ikon WiFi (fa-wifi)
        format_up   = "  %signal %essid %ip"
        format_down = "  down"
}

ethernet _first_ {
        # Ikon Ethernet (mdi-ethernet)
        format_up   = "󰈀 %ip (%speed)"
        format_down = "󰈀 down"
}

cpu_usage {
        # Ikon Chip (fa-microchip)
        format             = " %usage"
        max_threshold      = 75
        degraded_threshold = 50
}

cpu_temperature 0 {
        # Ikon Termometer (fa-thermometer-half)
        format        = " %degrees°C"
        path          = "/sys/class/thermal/thermal_zone1/temp"
        max_threshold = 75
}
