general {
        colors = true
        interval = 5
        color_good = "#b8bb26"
        color_degraded = "#fabd2f"
        color_bad = "#fb4934"
}

order += "memory"
order += "disk /"
order += "disk /home/me/Disk"
order += "ethernet tailscale0"
order += "tztime local"
order += "battery all"

memory {
        # Ikon RAM (mdi-memory)
        format             = "󰍛 %used/%total"
        threshold_degraded = "1G"
        format_degraded    = "󰍛 LOW: %free"
}

disk "/" {
        # Ikon Harddisk (fa-hdd-o)
        format = " Root: %avail"
}

disk "/home/me/Disk" {
        # Ikon Harddisk untuk partisi data
        format = " Data: %avail"
}

ethernet tailscale0 {
        # Ikon VPN/Network (mdi-vpn)
        format_up   = "󰖂 UP (%ip)"
        format_down = "󰖂 down"
}

tztime local {
        # Ikon Kalender dan Jam
        format =" %Y-%m-%d   %H:%M %Z"
}

battery all {
        # Mengganti Emoji dengan Ikon Vektor Solid Nerd Font
        format = "%status %percentage"
        format_down = " No battery"
        status_chr = " CHR"
        status_bat = " BAT"
        status_unk = " UNK"
        status_full = " FULL"
        path = "/sys/class/power_supply/BAT%d/uevent"
        low_threshold = 25
}
