conky.config = {
    background = true,
    use_xft = true,
    font = 'JetBrainsMono Nerd Font:size=9',
    xftalpha = 0.8,
    update_interval = 10,
    total_run_times = 0,
    own_window = true,
    own_window_colour = '#00000000',
    own_window_type = 'override',
    own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
    double_buffer = true,
    draw_shades = false,
    draw_outline = false,
    draw_borders = false,
    draw_graph_borders = false,
    default_color = '88ABC4',
    alignment = 'top_left',
    gap_x = 30,
    gap_y = 60,
    no_buffers = true,
    override_utf8_locale = true,
    use_spacer = 'right',
    maximum_width = 500,
}

conky.text = [[
${color 1793d1}    _             _      ${color 88abc4}_ _                  
${color 1793d1}   / \   _ __ ___| |__  ${color 88abc4}| (_)_ __  _   ___  __
${color 1793d1}  / _ \ | '__/ __| '_ \ ${color 88abc4}| | | '_ \| | | \ \/ /
${color 1793d1} / ___ \| | | (__| | | |${color 88abc4}| | | | | | |_| |>  < 
${color 1793d1}/_/   \_\_|  \___|_| |_|${color 88abc4}|_|_|_| |_|\__,_/_/\_\
${color 5a715c}
  [ @author girirahayu ]
${color}
${execp cat "/tmp/.${LOGNAME}_i3_daemon" 2>/dev/null}
${texeci 1800 ~/.config/conky/daemon > "/tmp/.${LOGNAME}_i3_daemon" 2>&1}
]]
